	AREA FACTORIAL, CODE, READONLY
	LDR r0, =SOURCE
	LDR r0, [r0]
	MOV r1, #1
LOOP
	MUL r2, r0, r1
	MOV r1, r2
	SUBS r0, r0, #1
	BNE LOOP
	LDR r0, =DEST
	STR r2, [r0]
STOP
	B STOP
	AREA SOURCEDATA, DATA, READONLY
SOURCE
	DCD 0x6
	AREA DESTDATA, DATA, READWRITE
DEST
	SPACE 32
	END