	AREA MULTIPLY, CODE, READONLY
	EXPORT LOAD
LOAD
	LDR r0, =SOURCE
	LDR r1, [r0, #4]
	LDR r0, [r0]
	MUL r2, r0, r1
	LDR r0, =DEST
	STR r2, [r0]
STOP
	B STOP
	AREA SOURCEDATA, DATA, READONLY
SOURCE
	DCD 0x1111, 0x2222
	AREA DESTDATA, DATA, READWRITE
DEST
	SPACE 32
	END