	AREA ONEZERO, CODE, READONLY
	LDR r0, =SOURCE
	LDR r0, [r0]
	MOV r1, #32
	MOV r2, #0
	LDR r3, =DEST
LOOP
	MOVS r0, r0, LSL #1
	BCS ZEROSKIP
	ADD r2, r2, #1
ZEROSKIP
	SUBS r1, r1, #1
	BNE LOOP
	STR r2, [r3]
	RSB r2, r2, #32
	STR r2, [r3, #4]
STOP
	B STOP
	AREA SOURCEDATA, DATA, READONLY
SOURCE
	DCD 0x12345678
	AREA DESTDATA, DATA, READWRITE
DEST
	DCD 0x0
	END