	AREA RAM, CODE, READONLY
	EXPORT __main
	ENTRY
__main
	LDR r0, =DATA
	LDR r0, [r0]
	LDR r1, =RAMLOC
	STR r0, [r1]
STOP
	B STOP
	AREA DATALOC, DATA, READONLY
DATA
	DCD 0x12345678
	AREA RAMDATA, DATA, READWRITE
RAMLOC
	DCD 0x0
	END