	AREA TEN_SUM, CODE, READONLY
	LDR r0, =SOURCE
	LDR r1, [r0]
	MOV r2, #0
LOOP
	ADD r2, r2, r1
	SUBS r1, r1, #1
	BNE LOOP
	LDR r0, =DEST
	STR r2, [r0]
STOP
	B STOP
	AREA SOURCEDATA, DATA, READONLY
SOURCE
	DCD 0xA
	AREA DESTDATA, DATA, READWRITE
DEST
	SPACE 32
	END